### PR TITLE
Edits to exam practice

### PR DESCRIPTION
**Pull request by spencerlyon2**
This is a work an progress and not ready to be merged. I'll comment and let you know when I think my edits are done.

So far I've only done structural changes and haven't reviewed the content. The changes are:

- I gave each subproblem a number instead of a blank bullet point so it is easier to refer to.
- I made the number of blank cells after each question consistent.

### CODE REVIEW

**Comment by spencerlyon2** [comment]
OK I'm done now.

My second commit made the following changes:

- Made sure that if in a later problem we refer to a variable created in an earlier problem, we mention where the variable was supposed to have been created.
- Minor wording adjustment to give a hint on the very last problem
- Asked students to do the renaming of the columns of `debt` using a list and a dict.

**Comment by cc7768** [comment]
I think this is great for a review of the material we have covered. I couldn't think of anything to change or add.

**Comment by spencerlyon2** [comment]
Great.

Dave, if you are happy with these changes hit that green "Merge Pull Request" button and these changes will be brought into the master brach.

**Comment by spencerlyon2** [comment]
That was fast!




// Spencer

On March 21, 2016 at 10:16:27 AM, Dave Backus (notifications@github.com) wrote:

Merged #13.

**Pull request merged**
